apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJuZ29jdHRob2FuZyIsInBhc3N3b3JkIjoibWl4bWFzdGVyIiwiZW1haWwiOiJuZ29jdHRob2FuZ0BrbXMtdGVjaG5vbG9neS5jb20iLCJhdXRoIjoiYm1kdlkzUjBhRzloYm1jNmJXbDRiV0Z6ZEdWeSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2022-02-14T10:01:55Z"
  name: kms-spring-practice-regcred
  namespace: default
  resourceVersion: "48399"
  uid: 9e6b5670-7f34-4f8a-a5c7-9e3eea5cca1b
type: kubernetes.io/dockerconfigjson
